server:
  port: 30500

spring:
  application:
    name: demo-limit
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.bus:
  limit:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local